name: LambdaSharp CI/CD

on:
  push:
    branches:
      - main
      - v*
      - WIP-v*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Set LambdaSharp environment variable
        run: echo "LAMBDASHARP=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      # CLI Tests
      - name: Test LambdaSharp.CloudFormation
        run: dotnet test --configuration Release Tests/Tests.LambdaSharp.CloudFormation

      - name: Test LambdaSharp.Modules
        run: dotnet test --configuration Release Tests/Tests.LambdaSharp.Modules

      # SDK Tests
      - name: Test LambdaSharp
        run: dotnet test --configuration Release Tests/Tests.LambdaSharp

      # Module Tests
      - name: Test LambdaSharp.Core
        run: dotnet test --configuration Release Modules/LambdaSharp.Core/Tests/Tests.ProcessLogEventsTests
